package com.eclipserealms.game.combat;

public enum SkillType {
    WARRIOR_SLASH, WARRIOR_SHIELD_BASH, WARRIOR_WHIRLWIND,
    MAGE_FIREBOLT, MAGE_FROST_NOVA, MAGE_ARCANE_BEAM,
    ROGUE_BACKSTAB, ROGUE_QUICK_STRIKE, ROGUE_SMOKE_STEP
}
